### ISSUE TITLE
meson build fails due to wrong contents of LINGUAS file

### ISSUE THREAD

**Issue by decathorpe** [elementary/capnet-assist#24]
For example, the "aa" locale is present in the LINGUAS file but there are no translations present for it, which leads to the following error in meson:

```
+ /usr/bin/ninja install -v -j16 -C x86_64-redhat-linux-gnu
ninja: Entering directory `x86_64-redhat-linux-gnu'
[0/1] /usr/bin/python3 /usr/bin/meson --internal install /builddir/build/BUILD/capnet-assist-0.2.1+git171002.200931.a25dfffc/x86_64-redhat-linux-gnu/meson-private/install.dat
msgfmt: error while opening "/builddir/build/BUILD/capnet-assist-0.2.1+git171002.200931.a25dfffc/po/aa.po" for reading: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 312, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 279, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/gettext.py", line 113, in run
    if gen_gmo(src_sub, bld_sub, langs) != 0:
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/gettext.py", line 66, in gen_gmo
    '-o', os.path.join(bld_sub, l + '.gmo')])
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msgfmt', '/builddir/build/BUILD/capnet-assist-0.2.1+git171002.200931.a25dfffc/po/aa.po', '-o', '/builddir/build/BUILD/capnet-assist-0.2.1+git171002.200931.a25dfffc/x86_64-redhat-linux-gnu/po/aa.gmo']' returned non-zero exit status 1.
```

I have no idea why the travis build works despite this.

**Comment by tintou** [comment]
latest meson became more pedantic about missing .po files

**Comment by decathorpe** [comment]
Please re-open. The pushed "fix" wasn't enough, it just pushes the error to later in the build process. Because some of the translations are empty, meson doesn't generate .gmo files for them, but because they are listed in LINGUAS, it still tries to install them. This is the new error message:

```
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 312, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 279, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/gettext.py", line 115, in run
    do_install(src_sub, bld_sub, dest, options.pkgname, langs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/gettext.py", line 82, in do_install
    shutil.copyfile(srcfile, outfile)
  File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '(...)/build/po/aa.gmo'
```

Why not just drop "empty" translations from LINGUAS?

**Comment by tintou** [comment]
Okay, this is the right fix
https://github.com/elementary/capnet-assist/pull/26
dropping languages isn't the right solution, then you have unused file
